### PR TITLE
Validate relevant CA only

### LINKED ISSUE #56: Library crashes if there are expired Trusted CA certs configured
It could be a warning, but not a crash just because one day (today) we have an expired cert not removed from production.

```
"error": "java.security.cert.CertificateExpiredException: NotAfter: Mon Mar 18 00:00:00 EET 2024",
    "stack": [
      ".CertificateValidity.valid(Unknown Source)",
      "java.base/sun.security.x509.X509CertImpl.checkValidity(Unknown Source)",
      ".certificateIsValidOnDate(CertificateValidator.java:52)",
      "eu.webeid.security.certificate.CertificateValidator.trustedCACertificatesAreValidOnDate(CertificateValidator.java:62)",
      ".SubjectCertificateExpiryValidator.validateCertificateExpiry(SubjectCertificateExpiryValidator.java:56)",
      ".certvalidators.SubjectCertificateValidatorBatch.executeFor(SubjectCertificateValidatorBatch.java:44)",
      ".validateToken(AuthTokenValidatorImpl.java:161)",
      "eu.webeid.security.validator.AuthTokenValidatorImpl.validate(AuthTokenValidatorImpl.java:122)",
      "(WebEidClient.kt:29)",
...
```

The problem appeared today with expired KLASS3 2010 certs.

### PR DESCRIPTION
**Pull request by mrts**
WE2-913
    
Modify the certificate validation process to only check the expiration of CA certificate that is directly part of the user's certificate chain. This prevents service interruptions caused by expired but unrelated CA certificates.
    
Signed-off-by: Mart Somermaa <mrts@users.noreply.github.com>

Fixes #56

### CODE REVIEW

File: src/test/java/eu/webeid/security/validator/AuthTokenCertificateTest.java [hunk 1]
```diff
@@ -229,6 +229,7 @@ void whenUserCertificateIsNotYetValid_thenValidationFails() {
     }
 
     @Test
+    @Disabled("It is no longer feasible to check if trusted CA certificate is valid as subject certificate validity is checked before")
```
Comment (metsma) [inline src/test/java/eu/webeid/security/validator/AuthTokenCertificateTest.java:232]: Why not remove the test then?

Comment (mrts) [reply src/test/java/eu/webeid/security/validator/AuthTokenCertificateTest.java]: Thanks, fair point. I modified and re-enabled the tests and added comments why they are still relevant. Also added `whenUnrelatedCACertificateIsExpired_thenValidationSucceeds()` explicitly for this case.

**Review by metsma — APPROVED** [review]
